### ISSUE TITLE
Providing a wrong master password yields an error instead of a wrong secret (as was the case previously)

### ISSUE THREAD

**Issue by rolfschr** [stef/pwdsphinx#15]
Hi,

I setup pwdsphinx and it works fine. In the past (not sure which commit, definitely before equihash was introduced), when providing the 'wrong' password to retrieve a secret, I would simply get a wrong secret; now I get an error message (see below). I am not sure whether this is intended or not. I just wanted to highlight this. Feel free to close this issue if this is expected behavior.

Thanks

```bash
bash-4.4$ sphinx init
bash-4.4$ ls ./datadir/masterkey
./datadir/masterkey
bash-4.4$ printf 'm' | sphinx create user site uld 10 # "m" is the master password
your ☆☆☆☆ (0/4) master password can be online recovered in 7 minutes, and offline in less than a second, trying ~12 guesses
UeZzrVEtox
bash-4.4$ printf 'm' | sphinx get user site
UeZzrVEtox
bash-4.4$ printf 'wrongmasterpassword' | sphinx get user site
Traceback (most recent call last):
  File "/nix/store/z1d50cbhzrjz4pinmsyvalh7444d10qr-python3.8-pwdsphinx-7fde7bb/bin/.sphinx-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/z1d50cbhzrjz4pinmsyvalh7444d10qr-python3.8-pwdsphinx-7fde7bb/lib/python3.8/site-packages/pwdsphinx/sphinx.py", line 673, in main
    ret = cmd(s, pwd, *args)
  File "/nix/store/z1d50cbhzrjz4pinmsyvalh7444d10qr-python3.8-pwdsphinx-7fde7bb/lib/python3.8/site-packages/pwdsphinx/sphinx.py", line 385, in get
    raise ValueError("bad checkdigit")
ValueError: bad checkdigit
```

**Comment by stef** [comment]
yes, this is intentional, we created a checkdigit, which is a UX feature, we store a 5 bits of a hash of the result of the sphinx protocol, which is supposed to help users realize they misstyped their master password. this checkdigit being only 5 bits means that this does not decrease the key-space significantly, but also means that 1/32 typos will still be false positives. we believe this does not reduce security significantly since the total key-space is 2^256 and this is reduced to 2^251 by this feature. however this does introduce a short-cut to not check a bunch of candidates, and thus it can be argued it eliminates the information theoretical security guarantee that sphinx provides. currently this feature is mandatory, but in order to restore information theoretical security and decrease UX we will make this optional. thank you very much for triggering this train of thought :)

**Comment by stef** [comment]
i believe this commit: https://github.com/stef/pwdsphinx/commit/3c37d991272ed65febd10b33b4e49a00751a1a5e fixes this issue.
